# Day 3 Assignment | Shubham Prakash

Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
arr=np.array(range(2,50,3))
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


 Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
import numpy as DK

In [3]:
k=[]
l=[]

print("Enter five values for first list")
for i in range(1,6):
    x=input(i)
    k.append(x)

print("Enter five values for second list")
for i in range(1,6):
    x=input(i)
    l.append(x)

arr1=DK.array([k])
arr2=DK.array([l])


print(" ")
print(" Concatination of two arrays")
print(" ")
arr_con=DK.concatenate([arr1,arr2])
print(arr_con)

print(" ")
print("sorting")
print(" ")
print(DK.sort(arr_con))


    


Enter five values for first list
15
26
33
43
52
Enter five values for second list
15
26
33
48
54
 
 Concatination of two arrays
 
[['5' '6' '3' '3' '2']
 ['5' '6' '3' '8' '4']]
 
sorting
 
[['2' '3' '3' '5' '6']
 ['3' '4' '5' '6' '8']]


Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size of unique items?

In [32]:

arr=DK.array([[ 1, 2, 3],[ 4, 5, 6],[7,8,9]])
 
print("dimension of array: ",arr.ndim)
print(" ")
print("Size of array: ",arr.size)
 



dimension of array:  2
 
Size of array:  9


Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [74]:
arr_re=DK.array([1,2,3,4,5,6])
print(arr_re)
print(" ")
print("1D array converted into 2D array")
re=DK.reshape(arr_re,(2,3))
print(re)
print(" ")

# DK.newaxis
row=arr_re[DK.newaxis,:]
print("one row six column")
print(row.shape)
col=arr_re[:,DK.newaxis]
print("six rows six columns")
print(col.shape)



[1 2 3 4 5 6]
 
1D array converted into 2D array
[[1 2 3]
 [4 5 6]]
 
one row six column
(1, 6)
six rows six columns
(6, 1)
